remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: 経済指標カレンダー
description: an Alexa Skill that keeps you informed about the latest economic indicators announced each day.
